modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU AGPL 3.0"

[[mods]]
modId = "discover"
version = "${version}"
displayName = "Discover"
authors = "Tenzin <3"
credits = "ecarrascon for Structure Credits and Nick Young for Traveler's Titles"
description = '''
Adds some cute titles when you enter a biome / dimension / structure !
'''
logoFile = "icon.png"

[[dependencies.discover]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.discover]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.discover]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.discover]]
modId = "fzzy_config"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"